# Generated by Django 3.1.5 on 2021-02-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210127_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='persons/tmp.jpg', upload_to='persons'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='persons/tmp.jpg', upload_to='persons'),
        ),
    ]
